# Generated by Django 5.2.6 on 2026-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planer',
            name='done',
            field=models.TextField(null=True),
        ),
    ]
